[mgr]
show_hidden = true

[tasks]
image_bound = [10000, 10000]

[opener]
set-wallpaper = [ 
    { run = "set-wallpaper %s1", for = "linux", desc = "Set as wallpaper" }
]
zathura = [
    { run = "zathura %s", orphan = true, for = "linux", desc = "Open in zathura" }
]

[open]
prepend_rules = [
    { mime = "image/*", use = [ "open", "reveal", "set-wallpaper" ] },
    { mime = "application/pdf", use = [ "zathura", "open" ] }
]

